### ISSUE TITLE
MD024 `siblings_only` works from conf file but not from `--set`

### ISSUE THREAD

**Issue by cpswan** [jackdewinter/pymarkdown#1000]
I've been trying to use `--set plugins.md024.siblings_only=$!True` with no success, whilst if I copy the config fragment from the tests into a file it works as expected:

`conf`
```
{"plugins": {"md024": {"siblings_only": True}}}
```

`pymarkdown -c conf scan myfile.md` 😃 
`pymarkdown --set plugins.md024.siblings_only=$!True scan myfile.md` 😢 
or `pymarkdown -s plugins.md024.siblings_only=$!True scan myfile.md` also 😢

**Comment by jackdewinter** [comment]
I am going to add requests for more information from filed issues, so hopefully that will help.

Is your OS windows?  If so, you need to use "plugins.md024.siblings_only=$!True" to keep the parameter together, otherwise it gets split into two parts.  If so, you should get a 
```
error: argument --set/-s: invalid verify_manual_property_form value: 'plugins.md024.siblings_only'
```

To be clear, using your commands as a template, used these two files (remove the .txt for local use)
[t1.cfg.txt](https://github.com/jackdewinter/pymarkdown/files/14644460/t1.cfg.txt)
[t1.md.txt](https://github.com/jackdewinter/pymarkdown/files/14644461/t1.md.txt)

and a command line of `pymarkdown --set "plugins.md024.siblings_only=$!True" scan t1.md`

and things looked good here.

**Comment by jackdewinter** [comment]
Added this into the new documentation: https://pymarkdown.readthedocs.io/en/latest/advanced_configuration/#special-characters-and-shells

**Comment by cpswan** [comment]
Thanks @jackdewinter
