### ISSUE TITLE
Can't set a boolean on the CLI

### ISSUE THREAD

**Issue by sometato** [jackdewinter/pymarkdown#266]
I have a `CHANGELOG.md` file which is hanging up on MD024. I'm not sure what the best practice is for this.

I'm using pymarkdown with pre-commit, so have just been using CLI options.

```
$ pymarkdownlnt --strict-config --disable-rules=MD013 --set plugins.md024.siblings_only=True scan .
BadPluginError encountered while configuring plugins:The value for property 'plugins.md024.siblings_only' must be of type 'bool'.
```

I haven't found any variation here that works.

Thank you!

**Comment by jackdewinter** [comment]
Check this link out: https://github.com/jackdewinter/pymarkdown/blob/main/docs/advanced_configuration.md#specifying-configuration-types

I am trying to find the time to work on the configuration package to introduce conversions.  If you can let me know where you looked in the docs, maybe I can put a better link to that for now.  Also, did you check the (sparse) FAQ doc?

Basically, if you can help me figure out how to document this better, it would be appreciated.

Also, when you say "hanging up on", would it be correct to infer that it is not scanning it properly?  Could you attach a copy of the `CHANGELOG.md` file that you are suing, so I can see what the issue is?
