### ISSUE TITLE
How to make use of extensions.front-matter.enabled=$!True

### ISSUE THREAD

**Issue by LKirst** [jackdewinter/pymarkdown#637]
When I run  `pymarkdown -s extensions.front-matter.enabled=true scan test.md` with the following test file, I get output which suggests, that the font-matter is not taken into account in the parsing of my example file:

The file: 
```
---
Title: My Markdown document
Date: 2023-03-28
---

# First level heading

## Second level heading

This is my Markdown document.

```

The output:
```
test.md:1:1: MD041: First line in file should be a top level heading (first-line-heading,first-line-h1)
test.md:2:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 0; Above] (blanks-around-headings,blanks-around-headers)
test.md:6:1: MD003: Heading style should be consistent throughout the document. [Expected: setext; Actual: atx] (heading-style,header-style)
test.md:8:1: MD003: Heading style should be consistent throughout the document. [Expected: setext; Actual: atx] (heading-style,header-style)

```

If the front-matter was recognized, my headings would all be consistent atx headings. What can I do to make pymarkdown (v0.9.9) recognize this?

Thank you for your help!

**Comment by jackdewinter** [comment]
Added a couple of new test cases to be sure, but try changing your third parameter to `extensions.front-matter.enabled=$!True`.  Can you confirm that works for you?

So, that fact that you found the right setting means that the first half of that is okay.  That is, how to enable it is specified.  Can you comment on whether or not it is specified clearly? Any suggestions on how to make it better.

On the second half, the value, there is [this section](https://github.com/jackdewinter/pymarkdown/blob/main/docs/advanced_configuration.md#specifying-configuration-types) in the advanced configuration document.  Maybe an extra link to that section from where the configuration is located?  Just worried that if I do that for one, I need to place it in at least 5-6 other places for the same reason.   Thoughts?

From a design point of view, I strongly believe in strongly typed configuration.  I have seen untyped fail too many times in unpredictable ways.  But willing to bend.

**Comment by LKirst** [comment]
Thank you very much for your answer. 

Using your parameter, I get the same result (using the test file content I used in my first post):

```
$ pymarkdown -s extensions.front-matter.enabled=$!True scan test.md
test.md:1:1: MD041: First line in file should be a top level heading (first-line-heading,first-line-h1)
test.md:2:1: MD022: Headings should be surrounded by blank lines. [Expected: 1; Actual: 0; Above] (blanks-around-headings,blanks-around-headers)
test.md:6:1: MD003: Heading style should be consistent throughout the document. [Expected: setext; Actual: atx] (heading-style,header-style)
test.md:8:1: MD003: Heading style should be consistent throughout the document. [Expected: setext; Actual: atx] (heading-style,header-style)
```
Is this the output I should see? 

What would have helped me understand the typed configuration is a complete example using the necessary syntax. You give the following example: 
`pymarkdown --stack-trace -s log.level=INFO -s log.file=log.txt scan examples`
Perhaps you could also give an example like this which uses a boolean?

**Comment by jackdewinter** [comment]
Interesting.  What OS and version are you running that command on and in what shell? Can you try putting quotes around the argument and turning on strict mode? i.e. `pymarkdown --strict-config -s "extensions.front-matter.enabled"=$!True scan test.md`

I primarily program on Windows, but also use WSL to verify linux issues. And note that this is a fun one to debug because the configuration needs to be parsed before logging can properly be done, so its somewhat in a no-mans land.

What I do know. I have a "sandbox" that I test all releases in.  When I go to that sandbox and enter that command:

```
sandbox>pipenv run pymarkdown -s extensions.front-matter.enabled=$!True scan ..\pymarkdown\test\resources\pragmas\extensions_issue_637.md

sandbox>
```

Also, when I run: `pymarkdown --log-level DEBUG -s extensions.front-matter.enabled=$!True scan`,  I get a lot of output at the start including:

```
DEBUG:pymarkdown.extension_manager.extension_manager:Extension 'front-matter'
DEBUG:application_properties.application_properties:property_name=extensions.front-matter.enabled
DEBUG:pymarkdown.extension_manager.extension_manager:Extension specific key 'enabled' found, value is 'True'.
INFO:pymarkdown.extension_manager.extension_manager:extension front-matter: enabled=True
```

This confirms for me that it believes things are formed properly and is enabling the extension.  Can you use that that command line `pymarkdown --log-level DEBUG -s extensions.front-matter.enabled=$!True scan` for me and paste that section of the debug logs here?

**Comment by jackdewinter** [comment]
Also, just merged in some changes to advanced configuration with some examples.  Let me know if those are what you had in mind.

**Comment by LKirst** [comment]
Thank you for the additions to the documentation. They help me a lot.

I am on Win10 with bash, but as far as I can tell, I get the same results from Powershell.

Here is the file I get from calling `$ pymarkdown --strict-config --log-level DEBUG -s extensions-front-matter.enabled=$!True scan test.md >> log.txt` from bash.

[log.txt](https://github.com/jackdewinter/pymarkdown/files/11130531/log.txt)

**Comment by jackdewinter** [comment]
Just to check, did you use the command line above, or one with `extensions.front-matter.enabled`?

**Comment by LKirst** [comment]
👍  I used the command line above (`$ pymarkdown --strict-config --log-level DEBUG -s extensions-front-matter.enabled=$!True scan test.md >> log.txt`)

**Comment by jackdewinter** [comment]
okay, maybe I am not communicating something properly.  the line that you supplied has `extensions-front-matter.enabled` as the key instead of `extensions.front-matter.enabled`.   It is `extensions`, then `front-matter`, then `enabled`.  You have the right separator between the second and third items, but not the first and second.

**Comment by LKirst** [comment]
Thank you so much! I don't know how I missed that.

With Powershell, I can directly copy your examples:
`pymarkdown --strict-config --set extensions.front-matter.enabled=$!True scan test.md`

With bash, I have to escape the dollar sign:
`pymarkdown --strict-config --set extensions.front-matter.enabled=\$!True scan test.md`
