### ISSUE TITLE
Issues with Unordered list indentation

### ISSUE THREAD

**Issue by finbaromahony** [jackdewinter/pymarkdown#683]
# Description
When linting markdown files with Unordered lists it will often complain if my desired indent is 4 spaces.

# Sample

```
# I am a test file

1. first item

    I am an explanation

    - I am a list of things
    - I am a continuation of said list

1. second item

end
```

# Expected result
No issues

# Actual result
```
pymarkdownlnt --config pymarkdown.cfg scan --recurse docs/
docs/xxxx/xxxx/blah.md:7:5: MD007: Unordered list indentation [Expected: 4, Actual=5] (ul-indent)
docs/xxxx/xxxx/blah.md:8:5: MD007: Unordered list indentation [Expected: 4, Actual=5] (ul-indent)
```

# Version
pymarkdownlnt          0.9.11

# Additional information
If I change the indent to 3 instead of 4 🤢 
Then there are no issues

**Comment by jackdewinter** [comment]
Took a quick look at this one, and [rule md007](https://github.com/jackdewinter/pymarkdown/blob/main/docs/rules/rule_md007.md) appears to be working properly.  In this case, the reason indent 3 works is because the "first item" is indented to 3, so the sublist is expected to start at 3.  

This rule is specifically to avoid "extra" spaces.  i.e. the lists are starting with "{space}-" when "-" would suffice.  If you do not like this rule, you are free to disable it.

Does that make sense?

**Comment by jackdewinter** [comment]
closing after no comments added.
